/*
 * Copyright 2010-2013 The Advance EU 7th Framework project consortium
 *
 * This file is part of Advance.
 *
 * Advance is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 * Advance is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Advance.  If not, see
 * <http://www.gnu.org/licenses/>.
 *
 */


package eu.advance.logistics.live.reporter.ws;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ImportSEIService", 
targetNamespace = "http://importdata.reporter.live.logistics.advance.eu/", 
wsdlLocation = "https://innovation.xen.emi.sztaki.hu/advance-live-reporter/importdata?wsdl")
public class ImportSEIService extends Service {
	/** */
	private static final String TARGET_NAMESPACE = "http://importdata.reporter.live.logistics.advance.eu/";

	/**
	 * Constructor, sets the WSDL location.
	 * @param wsdlLocation the WSDL location.
	 */
    public ImportSEIService(URL wsdlLocation) {
        super(wsdlLocation, new QName(TARGET_NAMESPACE, "ImportSEIService"));
    }
    /**
     * 
     * @return
     *     returns ImportSEI
     */
    @WebEndpoint(name = "ImportSEIPort")
    public ImportSEInterface getImportSEIPort() {
        return super.getPort(new QName(TARGET_NAMESPACE, "ImportSEIPort"), ImportSEInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImportSEI
     */
    @WebEndpoint(name = "ImportSEIPort")
    public ImportSEI getImportSEIPort(WebServiceFeature... features) {
        return super.getPort(new QName(TARGET_NAMESPACE, "ImportSEIPort"), ImportSEI.class, features);
    }

}
