/*
 * Copyright 2010-2012 The Advance EU 7th Framework project consortium
 *
 * This file is part of Advance.
 *
 * Advance is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 * Advance is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Advance.  If not, see
 * <http://www.gnu.org/licenses/>.
 *
 */
package eu.advance.logistics.flow.engine.controlcenter;

import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import org.openide.windows.WindowManager;

/**
 *
 * @author TTS
 */
public class ListDialog extends javax.swing.JDialog {

    private TableModel tableModel;

    public ListDialog(TableModel tm) {
        super(WindowManager.getDefault().getMainWindow(), true);
        this.tableModel = tm;
        initComponents();

        Dimension dim = new Dimension(600, 400);
        setPreferredSize(dim);
        setMinimumSize(dim);
        setSize(dim);

        EngineController ec = EngineController.getInstance();
        engineLable.setText(ec.getEngineAddress());
        versionLabel.setText(ec.getEngineVersion());
        
        tableModel.addTableModelListener(new LabelCounterUpdater(recordsCounter, tableModel));
        getRootPane().setDefaultButton(confirmButton);
    }
    
    JTable getTable() {
        return table;
    }
    
    JButton getConfirmButton() {
        return confirmButton;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        engineLable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        recordLabel = new javax.swing.JLabel();
        recordsCounter = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        refreshButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 100));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        table.setModel(tableModel);
        table.setFillsViewportHeight(true);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        headerPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ListDialog.class, "ListDialog.jLabel1.text_1")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        headerPanel.add(jLabel1, gridBagConstraints);

        engineLable.setFont(engineLable.getFont().deriveFont(engineLable.getFont().getStyle() | java.awt.Font.BOLD));
        engineLable.setText("https://localhost:8081/ADVANCE_DEV"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.weightx = 1.0;
        headerPanel.add(engineLable, gridBagConstraints);

        jLabel3.setText(org.openide.util.NbBundle.getMessage(ListDialog.class, "ListDialog.jLabel3.text_1")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 5);
        headerPanel.add(jLabel3, gridBagConstraints);

        versionLabel.setFont(versionLabel.getFont().deriveFont(versionLabel.getFont().getStyle() | java.awt.Font.BOLD));
        versionLabel.setText("0.00.001"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        headerPanel.add(versionLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(headerPanel, gridBagConstraints);

        recordLabel.setText(org.openide.util.NbBundle.getMessage(ListDialog.class, "ListDialog.recordLabel.text_1")); // NOI18N
        infoPanel.add(recordLabel);

        recordsCounter.setFont(recordsCounter.getFont().deriveFont(recordsCounter.getFont().getStyle() | java.awt.Font.BOLD));
        recordsCounter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        recordsCounter.setText("3"); // NOI18N
        infoPanel.add(recordsCounter);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        getContentPane().add(infoPanel, gridBagConstraints);

        buttonsPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        refreshButton.setText(org.openide.util.NbBundle.getMessage(ListDialog.class, "ListDialog.refreshButton.text_1")); // NOI18N
        buttonsPanel.add(refreshButton);

        confirmButton.setText(org.openide.util.NbBundle.getMessage(ListDialog.class, "ListDialog.confirmButton.text")); // NOI18N
        buttonsPanel.add(confirmButton);

        closeButton.setText(org.openide.util.NbBundle.getMessage(ListDialog.class, "ListDialog.closeButton.text_1")); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(closeButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        getContentPane().add(buttonsPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel engineLable;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel recordLabel;
    private javax.swing.JLabel recordsCounter;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTable table;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
