/*
 * Copyright 2010-2012 The Advance EU 7th Framework project consortium
 *
 * This file is part of Advance.
 *
 * Advance is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 * Advance is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Advance.  If not, see
 * <http://www.gnu.org/licenses/>.
 *
 */
package eu.advance.logistics.flow.engine.controlcenter;

/**
 *
 * @author TTS
 */
public class UsersDetailDialog extends javax.swing.JDialog {

    /** Creates new form UsersDetailDialog */
    public UsersDetailDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        engineLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        detailsPane = new javax.swing.JTabbedPane();
        generalPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cretedLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        modifiedLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        leftPanel = new javax.swing.JPanel();
        nameText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pagerText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dateCombo = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        numberCombo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        mailText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        timeCombo = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        thousandText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        decimalText = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        passwordText = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        keystoreCombo = new javax.swing.JComboBox();
        manageButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        aliasText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        rightsPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        idLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cretedLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        modifiedLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rightsTable = new javax.swing.JTable();
        recordLabel1 = new javax.swing.JLabel();
        recordsCounter1 = new javax.swing.JLabel();
        realmsPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        idLabel2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cretedLabel2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        modifiedLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        realmsTable = new javax.swing.JTable();
        recordLabel = new javax.swing.JLabel();
        recordsCounter = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        closeButton = new javax.swing.JButton();
        saveCloseButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel1.text")); // NOI18N

        engineLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        engineLabel.setText("https://localhost:8081/ADVANCE_DEV"); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel3.text")); // NOI18N

        versionLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        versionLabel.setText("0.00.001"); // NOI18N

        detailsPane.setName(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.GeneralPanel.title")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel5.text")); // NOI18N

        idLabel.setText("1"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel6.text")); // NOI18N

        cretedLabel.setText("2011-09-19  [Joe]"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel8.text")); // NOI18N

        modifiedLabel.setText("2011-09-19  [Joe]"); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel7.text")); // NOI18N

        jLabel10.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel10.text")); // NOI18N

        jLabel12.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel12.text")); // NOI18N

        dateCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel14.text")); // NOI18N

        numberCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(nameText, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(numberCombo, 0, 223, Short.MAX_VALUE))
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(pagerText, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pagerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(numberCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel9.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel9.text")); // NOI18N

        jLabel11.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel11.text")); // NOI18N

        jLabel13.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel13.text")); // NOI18N

        timeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel15.text")); // NOI18N

        jLabel16.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel16.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(mailText))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(timeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(thousandText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(decimalText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {decimalText, thousandText});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(timeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(thousandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(decimalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jRadioButton1.setSelected(true);
        jRadioButton1.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jRadioButton1.text")); // NOI18N

        jRadioButton2.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jRadioButton2.text")); // NOI18N
        jRadioButton2.setEnabled(false);

        jLabel17.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel17.text")); // NOI18N
        jLabel17.setEnabled(false);

        keystoreCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        keystoreCombo.setEnabled(false);

        manageButton.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.manageButton.text")); // NOI18N
        manageButton.setEnabled(false);

        jLabel18.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel18.text")); // NOI18N
        jLabel18.setEnabled(false);

        aliasText.setEnabled(false);

        jLabel19.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel19.text")); // NOI18N

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                            .addGroup(generalPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(idLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(cretedLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(modifiedLabel))
                            .addGroup(generalPanelLayout.createSequentialGroup()
                                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1))
                        .addGap(18, 18, 18)
                        .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordText, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(aliasText, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(keystoreCombo, 0, 314, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(manageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idLabel)
                    .addComponent(jLabel8)
                    .addComponent(modifiedLabel)
                    .addComponent(jLabel6)
                    .addComponent(cretedLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(keystoreCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(aliasText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        detailsPane.addTab(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.generalPanel.TabConstraints.tabTitle"), generalPanel); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel20.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel20.text")); // NOI18N

        idLabel1.setText("1"); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel21.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel21.text")); // NOI18N

        cretedLabel1.setText("2011-09-19  [Joe]"); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel22.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel22.text")); // NOI18N

        modifiedLabel1.setText("2011-09-19  [Joe]"); // NOI18N

        rightsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Rights", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(rightsTable);
        rightsTable.getColumnModel().getColumn(0).setResizable(false);
        rightsTable.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.rightsTable.columnModel.title0")); // NOI18N
        rightsTable.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.rightsTable.columnModel.title1")); // NOI18N

        recordLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        recordLabel1.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.recordLabel1.text")); // NOI18N

        recordsCounter1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        recordsCounter1.setText("3"); // NOI18N

        javax.swing.GroupLayout rightsPanelLayout = new javax.swing.GroupLayout(rightsPanel);
        rightsPanel.setLayout(rightsPanelLayout);
        rightsPanelLayout.setHorizontalGroup(
            rightsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                    .addGroup(rightsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(idLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(cretedLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(modifiedLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightsPanelLayout.createSequentialGroup()
                        .addComponent(recordLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(recordsCounter1)))
                .addContainerGap())
        );
        rightsPanelLayout.setVerticalGroup(
            rightsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(idLabel1)
                    .addComponent(jLabel21)
                    .addComponent(cretedLabel1)
                    .addComponent(jLabel22)
                    .addComponent(modifiedLabel1))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recordsCounter1)
                    .addComponent(recordLabel1))
                .addContainerGap())
        );

        detailsPane.addTab(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.rightsPanel.TabConstraints.tabTitle"), rightsPanel); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel23.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel23.text")); // NOI18N

        idLabel2.setText("1"); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel24.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel24.text")); // NOI18N

        cretedLabel2.setText("2011-09-19  [Joe]"); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel25.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.jLabel25.text")); // NOI18N

        modifiedLabel2.setText("2011-09-19  [Joe]"); // NOI18N

        realmsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Realm", "List", "Rename", "Delete", "Start", "Stop", "Insert", "Delete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        realmsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(realmsTable);
        realmsTable.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.realmsTable.columnModel.title0")); // NOI18N
        realmsTable.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.realmsTable.columnModel.title1")); // NOI18N
        realmsTable.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.realmsTable.columnModel.title2")); // NOI18N
        realmsTable.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.realmsTable.columnModel.title3")); // NOI18N
        realmsTable.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.realmsTable.columnModel.title4")); // NOI18N
        realmsTable.getColumnModel().getColumn(5).setHeaderValue(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.realmsTable.columnModel.title5")); // NOI18N
        realmsTable.getColumnModel().getColumn(6).setHeaderValue(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.realmsTable.columnModel.title6")); // NOI18N
        realmsTable.getColumnModel().getColumn(7).setHeaderValue(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.realmsTable.columnModel.title7")); // NOI18N

        recordLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        recordLabel.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.recordLabel.text")); // NOI18N

        recordsCounter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        recordsCounter.setText("8"); // NOI18N

        javax.swing.GroupLayout realmsPanelLayout = new javax.swing.GroupLayout(realmsPanel);
        realmsPanel.setLayout(realmsPanelLayout);
        realmsPanelLayout.setHorizontalGroup(
            realmsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, realmsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(realmsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                    .addGroup(realmsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(idLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(cretedLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(modifiedLabel2))
                    .addGroup(realmsPanelLayout.createSequentialGroup()
                        .addComponent(recordLabel)
                        .addGap(18, 18, 18)
                        .addComponent(recordsCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        realmsPanelLayout.setVerticalGroup(
            realmsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(realmsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(realmsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(idLabel2)
                    .addComponent(jLabel24)
                    .addComponent(cretedLabel2)
                    .addComponent(jLabel25)
                    .addComponent(modifiedLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(realmsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recordsCounter)
                    .addComponent(recordLabel))
                .addContainerGap())
        );

        detailsPane.addTab(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.realmsPanel.TabConstraints.tabTitle"), realmsPanel); // NOI18N

        closeButton.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.closeButton.text")); // NOI18N

        saveCloseButton.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.saveCloseButton.text")); // NOI18N

        saveButton.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.saveButton.text")); // NOI18N

        refreshButton.setText(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.refreshButton.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(detailsPane, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(engineLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(versionLabel))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refreshButton)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton)
                        .addGap(18, 18, 18)
                        .addComponent(saveCloseButton)
                        .addGap(18, 18, 18)
                        .addComponent(closeButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {closeButton, refreshButton, saveButton, saveCloseButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(engineLabel)
                    .addComponent(jLabel3)
                    .addComponent(versionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailsPane, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(saveCloseButton)
                    .addComponent(saveButton)
                    .addComponent(refreshButton))
                .addContainerGap())
        );

        detailsPane.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(UsersDetailDialog.class, "UsersDetailDialog.GeneralPanel.title")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aliasText;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel cretedLabel;
    private javax.swing.JLabel cretedLabel1;
    private javax.swing.JLabel cretedLabel2;
    private javax.swing.JComboBox dateCombo;
    private javax.swing.JTextField decimalText;
    private javax.swing.JTabbedPane detailsPane;
    private javax.swing.JLabel engineLabel;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JLabel idLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox keystoreCombo;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JTextField mailText;
    private javax.swing.JButton manageButton;
    private javax.swing.JLabel modifiedLabel;
    private javax.swing.JLabel modifiedLabel1;
    private javax.swing.JLabel modifiedLabel2;
    private javax.swing.JTextField nameText;
    private javax.swing.JComboBox numberCombo;
    private javax.swing.JTextField pagerText;
    private javax.swing.JTextField passwordText;
    private javax.swing.JPanel realmsPanel;
    private javax.swing.JTable realmsTable;
    private javax.swing.JLabel recordLabel;
    private javax.swing.JLabel recordLabel1;
    private javax.swing.JLabel recordsCounter;
    private javax.swing.JLabel recordsCounter1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JPanel rightsPanel;
    private javax.swing.JTable rightsTable;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveCloseButton;
    private javax.swing.JTextField thousandText;
    private javax.swing.JComboBox timeCombo;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
